#!/usr/bin/env python3
"""Star- or path-mode farm: one Aura process, many rewrites, farm.jsonl.

Does not spawn Aura per sample. --rounds caps *attempts* (plant×rewrite
pairs sent to farm:run). Default --mode star. Path mode (--mode path
--depth 4) chains from post-source, then re-plants. Prints
keep/observe/illegal counts.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from apply import apply_patch, pick_bin, pick_lib
from catalog import load_plants, load_rewrites, pairs
from edsl_patch import (
    PatchError,
    aura_hash,
    scheme_string,
    sources_match,
    validate_patch,
)

OUT = ROOT / "data" / "raw" / "farm.jsonl"
OBSERVE = ROOT / "data" / "raw" / "farm-observe.jsonl"


def seen_ids(path: Path) -> set[str]:
    ids: set[str] = set()
    if not path.is_file():
        return ids
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            ids.add(json.loads(line)["id"])
        except (json.JSONDecodeError, KeyError):
            continue
    return ids


def append_jsonl(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def emit_driver(
    plan: list[tuple[dict, dict, str]],
    *,
    mode: str = "star",
    depth: int = 4,
) -> str:
    """One Aura program: require farm, farm:run per plant group."""
    groups: list[tuple[dict, list[tuple[dict, str]]]] = []
    for plant, rw, name in plan:
        if groups and groups[-1][0]["id"] == plant["id"]:
            groups[-1][1].append((rw, name))
        else:
            groups.append((plant, [(rw, name)]))
    if mode == "path":
        chunked: list[tuple[dict, list[tuple[dict, str]]]] = []
        cap = max(1, min(depth, 4))
        for plant, rws in groups:
            for i in range(0, len(rws), cap):
                chunked.append((plant, rws[i : i + cap]))
        groups = chunked
    lines = [
        ";; generated by scripts/farm.py — one process",
        '(require "farm" all:)',
    ]
    if mode == "path":
        lines.append("(farm:star-mode! #f)")
    for plant, rws in groups:
        hashes = []
        for rw, name in rws:
            hashes.append(
                aura_hash(
                    {
                        "name": name,
                        "body": rw["body"],
                        "summary": rw["summary"],
                    }
                )
            )
        rw_list = " ".join(hashes)
        lines.append(f'(display "EDSL_PLANT {plant["id"]}")')
        lines.append("(newline)")
        lines.append(
            f"(farm:run {scheme_string(plant['source'])} (list {rw_list}))"
        )
    lines.append("")
    return "\n".join(lines)


def run_aura(driver: str, *, timeout: int) -> str:
    bin_path = pick_bin()
    lib = pick_lib()
    env = os.environ.copy()
    env["AURA_PATH"] = f"{ROOT / 'lib'}:{lib}"
    env["AURA_SANDBOX"] = env.get("AURA_SANDBOX") or "off"
    env["AURA_PIPELINE_STRICT"] = env.get("AURA_PIPELINE_STRICT") or "0"
    proc = subprocess.Popen(
        [str(bin_path), "-e", driver] if False else [str(bin_path)],
        cwd=ROOT,
        env=env,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
    )
    try:
        stdout, stderr = proc.communicate(driver, timeout=timeout)
    except subprocess.TimeoutExpired as e:
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except OSError:
            proc.kill()
        proc.wait()
        raise PatchError(f"aura timeout after {timeout}s") from e
    out = (stdout or "") + (("\n" + stderr) if stderr else "")
    if proc.returncode != 0 and "EDSL_SAMPLE" not in out and "EDSL_OBSERVE" not in out:
        raise PatchError(f"aura exit {proc.returncode}: {out[-2000:]}")
    return out


def parse_stdout(out: str) -> tuple[list[tuple[str, dict]], list[dict]]:
    """Return ([(plant_id, sample), ...], observes)."""
    samples: list[tuple[str, dict]] = []
    observes: list[dict] = []
    plant_id = ""
    for line in out.splitlines():
        if line.startswith("EDSL_PLANT "):
            plant_id = line[len("EDSL_PLANT ") :].strip()
        elif line.startswith("EDSL_SAMPLE "):
            samples.append((plant_id, json.loads(line[len("EDSL_SAMPLE ") :])))
        elif line.startswith("EDSL_OBSERVE "):
            observes.append(json.loads(line[len("EDSL_OBSERVE ") :]))
    return samples, observes


def make_id(plant: dict, rw: dict, name: str) -> str:
    return f"farm-{plant['id']}-{rw['id']}-{name}"


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    if not path.is_file():
        return rows
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def spot_check(path: Path, frac: float) -> int:
    """Re-apply a fraction of farm.jsonl keeps. Default frac=0.01."""
    rows = read_jsonl(path)
    if not rows:
        print(f"farm: spot-check empty {path}", file=sys.stderr)
        return 1
    if frac >= 1.0:
        chosen = rows
    else:
        n = max(1, int(round(len(rows) * frac)))
        chosen = rows[:n]
    fail = 0
    for row in chosen:
        src = (row.get("input") or {}).get("source")
        target = row.get("target")
        try:
            result = apply_patch(src, target)
        except (PatchError, TypeError) as e:
            print(f"farm: spot-check fail {row.get('id')}: {e}", file=sys.stderr)
            fail += 1
            continue
        if not result.get("ok"):
            print(f"farm: spot-check apply-not-ok {row.get('id')}", file=sys.stderr)
            fail += 1
            continue
        expected = (row.get("verify") or {}).get("expected_source")
        if expected and not sources_match(result.get("source") or "", expected):
            print(f"farm: spot-check mismatch {row.get('id')}", file=sys.stderr)
            fail += 1
    print(f"farm: spot-check n={len(chosen)} fail={fail} frac={frac} {path}")
    return 0 if fail == 0 else 1


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--rounds", type=int, default=24, help="cap on attempts (pairs), not keeps")
    p.add_argument("--timeout", type=int, default=120, help="whole Aura process timeout seconds")
    p.add_argument(
        "--mode",
        default="star",
        help="star (default, re-plant every rewrite) or path (chain post-source, depth cap 4)",
    )
    p.add_argument(
        "--depth",
        type=int,
        default=4,
        help="path-mode chain length before re-plant (capped at 4)",
    )
    p.add_argument("--limit-rewrites", type=int, default=0)
    p.add_argument("--out", type=Path, default=OUT)
    p.add_argument("--observe", type=Path, default=OBSERVE)
    p.add_argument("--spot-check", type=Path, default=None, help="re-apply keeps in this jsonl")
    p.add_argument(
        "--spot-frac",
        type=float,
        default=0.01,
        help="fraction of rows to re-apply (1.0 in tests; 0.01 default)",
    )
    args = p.parse_args(argv)

    if args.spot_check is not None:
        try:
            pick_bin()
        except SystemExit as e:
            print(str(e), file=sys.stderr)
            return 1
        return spot_check(args.spot_check, args.spot_frac)

    if args.mode not in ("star", "path"):
        print("error: --mode must be star or path", file=sys.stderr)
        return 2
    depth = max(1, min(args.depth, 4))

    try:
        pick_bin()
    except SystemExit as e:
        print(str(e), file=sys.stderr)
        return 1

    plants = load_plants()
    rewrites = load_rewrites()
    if args.limit_rewrites:
        rewrites = rewrites[: args.limit_rewrites]
    plan = pairs(plants, rewrites)[: args.rounds]
    if not plan:
        print("farm: zero attempts (empty catalog pairs)", file=sys.stderr)
        return 1

    seen = seen_ids(args.out)
    driver = emit_driver(plan, mode=args.mode, depth=depth)
    # One process for all attempts (stdin driver; no per-sample spawn).
    try:
        out = run_aura(driver, timeout=args.timeout)
    except PatchError as e:
        print(f"farm: {e}", file=sys.stderr)
        return 1

    samples, observes = parse_stdout(out)
    if not samples and not observes:
        print("farm: zero attempts parsed from aura stdout", file=sys.stderr)
        return 1

    keep = illegal = 0
    plants_by_id = {p["id"]: p for p in plants}
    rws_by_sum = {}
    for rw in rewrites:
        rws_by_sum.setdefault(rw["summary"], []).append(rw)
    chain_plant = ""
    chain_round = 0
    for plant_id, row in samples:
        target = row.get("target")
        try:
            validate_patch(target)
        except PatchError:
            illegal += 1
            continue
        synth = target[-1]
        name = synth.get("name")
        summary = synth.get("summary")
        plant = plants_by_id.get(plant_id) or {}
        rw = (rws_by_sum.get(summary) or [{}])[0]
        sid = make_id(plant or {"id": plant_id or "x"}, rw or {"id": summary}, name)
        if sid in seen:
            continue
        if "input" not in row or "source" not in (row.get("input") or {}):
            illegal += 1
            continue
        if not (row.get("verify") or {}).get("apply_ok"):
            illegal += 1
            continue
        row["id"] = sid
        if args.mode == "path":
            if plant_id != chain_plant:
                chain_plant = plant_id
                chain_round = 0
            chain_round += 1
            row["meta"] = {
                "chain": plant_id,
                "round": chain_round,
                "mode": "path",
            }
        append_jsonl(args.out, row)
        seen.add(sid)
        keep += 1

    for ob in observes:
        append_jsonl(args.observe, ob)

    print(
        f"farm: attempts={len(plan)} keep={keep} observe={len(observes)} "
        f"illegal={illegal} mode={args.mode} -> {args.out}"
    )
    return 0 if keep or observes or samples else 1


if __name__ == "__main__":
    raise SystemExit(main())
