#!/usr/bin/env python3
"""Star-, path-, or world-mode farm: one Aura process, many rewrites.

Does not spawn Aura per sample. --rounds caps *attempts* (plant×rewrite
pairs sent to farm:run). Default --mode star. Path mode (--mode path
--depth 4) chains from post-source, then re-plants.

World mode (--mode world --project twin-step|session-hot) steps a live
world / sess and keeps only if conjunction probes pass. Vacuous or
harmful bodies (sign-damp on sat-plant, kill-alive, keep=false) drop.
Do not lower probes to raise keep rate. Prints keep/observe/illegal counts.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from apply import apply_patch, pick_bin, pick_lib
from catalog import (
    PROJECTS_ROOT,
    is_noop,
    load_plants,
    load_project,
    load_rewrites,
    pairs,
    project_pairs,
)
from edsl_patch import (
    PatchError,
    aura_hash,
    scheme_string,
    sources_match,
    validate_patch,
)

OUT = ROOT / "data" / "raw" / "farm.jsonl"
OBSERVE = ROOT / "data" / "raw" / "farm-observe.jsonl"


def seen_ids(path: Path) -> set[str]:
    ids: set[str] = set()
    if not path.is_file():
        return ids
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            ids.add(json.loads(line)["id"])
        except (json.JSONDecodeError, KeyError):
            continue
    return ids


def append_jsonl(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def emit_driver(
    plan: list[tuple[dict, dict, str]],
    *,
    mode: str = "star",
    depth: int = 4,
) -> str:
    """One Aura program: require farm, farm:run per plant group."""
    groups: list[tuple[dict, list[tuple[dict, str]]]] = []
    for plant, rw, name in plan:
        if groups and groups[-1][0]["id"] == plant["id"]:
            groups[-1][1].append((rw, name))
        else:
            groups.append((plant, [(rw, name)]))
    if mode == "path":
        chunked: list[tuple[dict, list[tuple[dict, str]]]] = []
        cap = max(1, min(depth, 4))
        for plant, rws in groups:
            for i in range(0, len(rws), cap):
                chunked.append((plant, rws[i : i + cap]))
        groups = chunked
    lines = [
        ";; generated by scripts/farm.py — one process",
        '(require "farm" all:)',
    ]
    if mode == "path":
        lines.append("(farm:star-mode! #f)")
    for plant, rws in groups:
        hashes = []
        for rw, name in rws:
            hashes.append(
                aura_hash(
                    {
                        "name": name,
                        "body": rw["body"],
                        "summary": rw["summary"],
                    }
                )
            )
        rw_list = " ".join(hashes)
        lines.append(f'(display "EDSL_PLANT {plant["id"]}")')
        lines.append("(newline)")
        lines.append(
            f"(farm:run {scheme_string(plant['source'])} (list {rw_list}))"
        )
    lines.append("")
    return "\n".join(lines)


def run_aura(driver: str, *, timeout: int) -> str:
    bin_path = pick_bin()
    lib = pick_lib()
    env = os.environ.copy()
    env["AURA_PATH"] = f"{ROOT / 'lib'}:{lib}"
    env["AURA_SANDBOX"] = env.get("AURA_SANDBOX") or "off"
    env["AURA_PIPELINE_STRICT"] = env.get("AURA_PIPELINE_STRICT") or "0"
    proc = subprocess.Popen(
        [str(bin_path), "-e", driver] if False else [str(bin_path)],
        cwd=ROOT,
        env=env,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
    )
    try:
        stdout, stderr = proc.communicate(driver, timeout=timeout)
    except subprocess.TimeoutExpired as e:
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except OSError:
            proc.kill()
        proc.wait()
        raise PatchError(f"aura timeout after {timeout}s") from e
    out = (stdout or "") + (("\n" + stderr) if stderr else "")
    if proc.returncode != 0 and "EDSL_SAMPLE" not in out and "EDSL_OBSERVE" not in out:
        raise PatchError(f"aura exit {proc.returncode}: {out[-2000:]}")
    return out


def parse_stdout(out: str) -> tuple[list[tuple[str, dict]], list[dict]]:
    """Return ([(plant_id, sample), ...], observes)."""
    samples: list[tuple[str, dict]] = []
    observes: list[dict] = []
    plant_id = ""
    for line in out.splitlines():
        if line.startswith("EDSL_PLANT "):
            plant_id = line[len("EDSL_PLANT ") :].strip()
        elif line.startswith("EDSL_SAMPLE "):
            samples.append((plant_id, json.loads(line[len("EDSL_SAMPLE ") :])))
        elif line.startswith("EDSL_OBSERVE "):
            observes.append(json.loads(line[len("EDSL_OBSERVE ") :]))
    return samples, observes


def make_id(plant: dict, rw: dict, name: str) -> str:
    return f"farm-{plant['id']}-{rw['id']}-{name}"


def twin_should_keep(
    t0: float,
    t1: float,
    n_post: int,
    e0: float,
    e1: float,
    name: str,
    frozen: list[str],
    sat0: float | None = None,
    sat1: float | None = None,
    x2_pre: float | None = None,
    x2_post: float | None = None,
) -> bool:
    """Conjunction probes. Vacuous/harmful bodies must fail."""
    if name in frozen or name in ("step", "energy", "impulse"):
        return False
    if int(t1) != int(t0) + int(n_post):
        return False
    try:
        e0f, e1f = float(e0), float(e1)
    except (TypeError, ValueError):
        return False
    if e0f < 0 or e1f < 0 or e0f > 1e9 or e1f > 1e9:
        return False
    if not (e1f < e0f):
        return False
    if sat0 is not None and sat1 is not None:
        if float(sat1) > float(sat0) + (int(n_post) / 2):
            return False
    if x2_pre is not None and x2_post is not None:
        if abs(float(x2_post)) > max(abs(float(x2_pre)), 20.0):
            return False
    return True


def session_should_keep(
    pre: dict,
    post: dict,
    name: str,
    keep_flag: bool | None = True,
    q_ok: bool = True,
    k: int = 8,
) -> bool:
    """Identity + seq + numeric-q conjunction. keep=false / kill-alive drop."""
    if keep_flag is False:
        return False
    if q_ok is False:
        return False
    if name in ("*session*", "gate"):
        return False
    if pre.get("id") != post.get("id") or pre.get("fd") != post.get("fd"):
        return False
    if bool(pre.get("alive")) is not True or bool(post.get("alive")) is not True:
        return False
    if "seq" in pre or "seq" in post:
        d = int(post.get("seq") or 0) - int(pre.get("seq") or 0)
        if d not in (0, 1, int(k)):
            return False
    return True


def world_init_aura(plant: dict) -> str:
    """Plant-specific world_0. two-mass / sat-plant are not free-mass clones."""
    pid = str(plant.get("id") or "")
    src = plant.get("source") or ""
    if pid.endswith("two-mass") or '"x1"' in src:
        return '(hash "x1" 2 "v1" 1 "x2" -1 "v2" 0 "t" 0)'
    if pid.endswith("sat-plant") or '"sat"' in src:
        return '(hash "x" 2 "v" 1 "t" 0 "sat" 0)'
    return '(hash "x" 2 "v" 1 "t" 0)'


def _opt_num(v) -> float | None:
    if v is None or v is False:
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def path_intent_twin(obs: dict, prev: dict | None = None, *, refuse: bool = False) -> str:
    """Intent templates with measured numbers — never a hardcoded 12.4 demo."""
    t = obs.get("t")
    e1 = obs.get("energy")
    if refuse:
        e0 = (prev or {}).get("energy", e1)
        try:
            if float(e1) >= float(e0):
                return f"energy rose {e0}→{e1} at t={t}; do not mutate"
        except (TypeError, ValueError):
            pass
        return f"energy={e1} at t={t}; do not mutate"
    return f"energy={e1} at t={t}; reduce energy"


def path_intent_session(obs: dict, *, refuse: bool = False) -> str:
    sess = obs.get("session") or obs
    if refuse:
        return "alive still true but last q killed probe; refuse"
    return (
        f"session id={sess.get('id')} fd={sess.get('fd')} seq={sess.get('seq')}; narrow quote"
    )


def path_decide(
    pre: dict,
    post: dict | None,
    vertical: str,
    *,
    last: str = "",
    name: str = "control",
    frozen: list[str] | None = None,
    n_post: int = 40,
    k: int = 8,
    keep_flag: bool = True,
) -> str:
    """Path hop action: keep | worsen | refuse | cut.

    Last hop energy-up / sat / seq-jump → this hop is refuse gold (no mutate).
    Apply/t_break → cut. Keep-fail on identity/energy is worsen, not a positive.
    """
    if last == "worsen":
        return "refuse"
    if last in ("cut", "refuse"):
        return "cut"
    if not post or post.get("ok") is False:
        return "cut"
    frozen = list(frozen or [])
    if vertical == "twin":
        t0, t1 = pre.get("t"), post.get("t")
        if t0 is None or t1 is None or int(t1) != int(t0) + int(n_post):
            return "cut"
        if twin_should_keep(
            t0,
            t1,
            n_post,
            pre.get("energy"),
            post.get("energy"),
            name,
            frozen,
            sat0=_opt_num(pre.get("sat")),
            sat1=_opt_num(post.get("sat")),
            x2_pre=_opt_num(pre.get("x2")),
            x2_post=_opt_num(post.get("x2")),
        ):
            return "keep"
        return "worsen"
    pre_s = pre.get("session") or pre
    post_s = post.get("session") or post
    if session_should_keep(
        pre_s,
        post_s,
        name,
        keep_flag=keep_flag,
        q_ok=post.get("okq", True) is not False,
        k=k,
    ):
        return "keep"
    return "worsen"


def path_chain(plant: dict, rewrites: list[dict], depth: int, vertical: str) -> list[dict]:
    """Catalog rebinds for a path. sign-damp / jump-seq sit early so smoke can worsen."""
    prefer_twin = (
        "clip-u",
        "sign-damp",
        "pd",
        "damp-v",
        "clip-then-pd",
        "p-x",
        "coast-if-small",
        "pd-both",
    )
    prefer_sess = (
        "clip-abs",
        "jump-seq",
        "narrow",
        "seq-inc",
        "hold-mid",
        "flat-zero",
        "skew-bid",
        "sign-book",
    )
    prefer = prefer_twin if vertical == "twin" else prefer_sess
    by_sum = {rw.get("summary"): rw for rw in rewrites}
    name = "control" if vertical == "twin" else "tick"
    chain: list[dict] = []
    for summary in prefer:
        rw = by_sum.get(summary)
        if not rw:
            continue
        if is_noop(plant, rw, name):
            continue
        chain.append(rw)
        if len(chain) >= depth:
            break
    return chain


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    if not path.is_file():
        return rows
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def spot_check(path: Path, frac: float) -> int:
    """Re-apply a fraction of farm.jsonl keeps. Default frac=0.01."""
    rows = read_jsonl(path)
    if not rows:
        print(f"farm: spot-check empty {path}", file=sys.stderr)
        return 1
    if frac >= 1.0:
        chosen = rows
    else:
        n = max(1, int(round(len(rows) * frac)))
        chosen = rows[:n]
    fail = 0
    for row in chosen:
        src = (row.get("input") or {}).get("source")
        target = row.get("target")
        try:
            result = apply_patch(src, target)
        except (PatchError, TypeError) as e:
            print(f"farm: spot-check fail {row.get('id')}: {e}", file=sys.stderr)
            fail += 1
            continue
        if not result.get("ok"):
            print(f"farm: spot-check apply-not-ok {row.get('id')}", file=sys.stderr)
            fail += 1
            continue
        expected = (row.get("verify") or {}).get("expected_source")
        if expected and not sources_match(result.get("source") or "", expected):
            print(f"farm: spot-check mismatch {row.get('id')}", file=sys.stderr)
            fail += 1
    print(f"farm: spot-check n={len(chosen)} fail={fail} frac={frac} {path}")
    return 0 if fail == 0 else 1


def emit_twin_world_driver(plan: list[tuple[dict, dict, str]], n_pre: int = 40, n_post: int = 40) -> str:
    """Drive plant-specific world_0; print sat/x2; Python applies keep."""
    lines = [
        ";; world-mode twin-step",
        '(require "farm" all:)',
        "(define (num-or-false w k)",
        "  (try (let ((v (hash-ref w k))) (if (number? v) v #f)) (catch (e) #f)))",
    ]
    for plant, rw, name in plan:
        frozen = list(plant.get("frozen") or ["step", "energy"])
        if rw.get("keep") is False:
            continue
        if name in frozen or name in ("step", "energy", "impulse"):
            continue
        w0 = world_init_aura(plant)
        lines += [
            f"(set-code {scheme_string(plant['source'])})",
            "(eval-current)",
            f"(define *w* {w0})",
            "(define (go k)",
            "  (if (<= k 0) #t",
            "    (begin (set! *w* (step *w* (control *w*))) (go (- k 1)))))",
            f"(try (go {n_pre}) (catch (e) #f))",
            '(define *t0* (hash-ref *w* "t"))',
            "(define *e0* (energy *w*))",
            '(define *sat0* (num-or-false *w* "sat"))',
            '(define *x20* (num-or-false *w* "x2"))',
            f"(define *rb* (try (mutate:rebind {scheme_string(name)} {scheme_string(rw['body'])} {scheme_string(rw['summary'])}) (catch (e) #f)))",
            "(if *rb* (try (eval-current) (catch (e) #f)) #f)",
            f"(try (go {n_post}) (catch (e) (set! *w* #f)))",
            "(if (and *rb* *w*)",
            "  (begin",
            '    (define *t1* (hash-ref *w* "t"))',
            "    (define *e1* (energy *w*))",
            '    (define *sat1* (num-or-false *w* "sat"))',
            '    (define *x21* (num-or-false *w* "x2"))',
            f'    (display "WORLD_SAMPLE ")',
            "    (display (json-encode (hash \"id\" "
            + scheme_string(f"world-{plant['id']}-{rw['id']}")
            + ' "plant" '
            + scheme_string(plant["id"])
            + ' "rewrite" '
            + scheme_string(rw["id"])
            + ' "t0" *t0* "t1" *t1* "e0" *e0* "e1" *e1*',
            ' "sat0" *sat0* "sat1" *sat1* "x2_pre" *x20* "x2_post" *x21*',
            ' "name" '
            + scheme_string(name)
            + ' "summary" '
            + scheme_string(rw["summary"])
            + ' "source" '
            + scheme_string(plant["source"])
            + ' "body" '
            + scheme_string(rw["body"])
            + ")))",
            "    (newline))",
            '  (begin (display "WORLD_DROP apply") (newline)))',
        ]
    lines.append("")
    return "\n".join(lines)


def emit_session_world_driver(plan: list[tuple[dict, dict, str]], k: int = 8) -> str:
    """Drive (tick book sess); print pre/post sess. quote-only is not identity."""
    lines = [";; world-mode session-hot"]
    for plant, rw, name in plan:
        frozen = list(plant.get("frozen") or ["*session*", "gate"])
        if rw.get("keep") is False:
            continue
        if name in frozen or name in ("*session*", "gate"):
            continue
        lines += [
            f"(set-code {scheme_string(plant['source'])})",
            "(eval-current)",
            "(define *sess* *session*)",
            '(define *book* (hash "bid" 1 "ask" 3 "mid" 2 "spread" 2))',
            '(define *sid* (hash-ref *sess* "id"))',
            '(define *sfd* (hash-ref *sess* "fd"))',
            '(define *sal* (hash-ref *sess* "alive"))',
            '(define *sseq* (try (hash-ref *sess* "seq") (catch (e) 0)))',
            f"(define *rb* (try (mutate:rebind {scheme_string(name)} {scheme_string(rw['body'])} {scheme_string(rw['summary'])}) (catch (e) #f)))",
            "(if *rb* (try (eval-current) (catch (e) #f)) #f)",
            "(define *okq* #t)",
            "(define *out* #f)",
            "(define (go i)",
            "  (if (<= i 0) #t",
            "    (begin",
            "      (set! *out* (try (tick *book* *sess*) (catch (e) #f)))",
            '      (if (and *out* (number? (hash-ref *out* "q")))',
            '        (set! *sess* (hash-ref *out* "sess"))',
            "        (set! *okq* #f))",
            "      (go (- i 1)))))",
            f"(if *rb* (try (go {k}) (catch (e) (set! *okq* #f))) #f)",
            '(define *sid2* (hash-ref *sess* "id"))',
            '(define *sfd2* (hash-ref *sess* "fd"))',
            '(define *sal2* (hash-ref *sess* "alive"))',
            '(define *sseq2* (try (hash-ref *sess* "seq") (catch (e) 0)))',
            "(if *rb*",
            "  (begin (display \"WORLD_SAMPLE \")",
            "    (display (json-encode (hash \"id\" "
            + scheme_string(f"world-{plant['id']}-{rw['id']}")
            + ' "plant" '
            + scheme_string(plant["id"])
            + ' "rewrite" '
            + scheme_string(rw["id"])
            + ' "name" '
            + scheme_string(name)
            + ' "summary" '
            + scheme_string(rw["summary"])
            + ' "source" '
            + scheme_string(plant["source"])
            + ' "body" '
            + scheme_string(rw["body"])
            + ' "sid" *sid* "sfd" *sfd* "sal" *sal* "sseq" *sseq*'
            + ' "sid2" *sid2* "sfd2" *sfd2* "sal2" *sal2* "sseq2" *sseq2*'
            + ' "okq" *okq*)))',
            "    (newline))",
            "  (begin (display \"WORLD_DROP session\") (newline)))",
        ]
    lines.append("")
    return "\n".join(lines)


def run_world(args: argparse.Namespace) -> int:
    pid = args.project
    if pid not in ("twin-step", "session-hot"):
        print("error: --mode world requires --project twin-step|session-hot", file=sys.stderr)
        return 2
    plants, rewrites = load_project(pid)
    rewrites = [rw for rw in rewrites if rw.get("keep") is not False]
    plan = project_pairs(plants, rewrites)[: args.rounds]
    if args.limit_rewrites:
        rewrites = rewrites[: args.limit_rewrites]
        plan = project_pairs(plants, rewrites)[: args.rounds]
    plants_by_id = {p["id"]: p for p in plants}
    out_path = args.out if args.out != OUT else (
        ROOT / "data" / "raw" / f"farm-world-{pid}.jsonl"
    )
    keep = drop = 0
    seen = seen_ids(out_path)
    chunk = 8
    raw_parts = []
    for i in range(0, len(plan), chunk):
        slice_plan = plan[i : i + chunk]
        if pid == "twin-step":
            driver = emit_twin_world_driver(slice_plan)
        else:
            driver = emit_session_world_driver(slice_plan)
        try:
            raw_parts.append(run_aura(driver, timeout=min(args.timeout, 45)))
        except PatchError as e:
            print(f"farm: chunk {i} {e}", flush=True)
            drop += len(slice_plan)
            continue
    raw = "\n".join(raw_parts)
    for line in raw.splitlines():
        if line.startswith("WORLD_DROP"):
            drop += 1
            continue
        if not line.startswith("WORLD_SAMPLE "):
            continue
        rec = json.loads(line[len("WORLD_SAMPLE ") :])
        name = rec.get("name")
        plant = plants_by_id.get(rec.get("plant") or "") or {}
        if pid == "twin-step":
            frozen = list(plant.get("frozen") or ["step", "energy"])
            hot = list(plant.get("hot") or ["control"])
            sat0 = _opt_num(rec.get("sat0"))
            sat1 = _opt_num(rec.get("sat1"))
            x2_pre = _opt_num(rec.get("x2_pre"))
            x2_post = _opt_num(rec.get("x2_post"))
            if not twin_should_keep(
                rec["t0"],
                rec["t1"],
                40,
                rec["e0"],
                rec["e1"],
                name,
                frozen,
                sat0=sat0,
                sat1=sat1,
                x2_pre=x2_pre,
                x2_post=x2_post,
            ):
                drop += 1
                continue
            observe = {
                "t": rec["t0"],
                "energy": rec["e0"],
                "hot": hot,
                "frozen": frozen,
            }
            if sat0 is not None:
                observe["sat"] = sat0
            sample = {
                "id": rec["id"],
                "input": {
                    "source": rec["source"],
                    "observe": observe,
                },
                "target": [
                    {"kind": "query", "op": "find", "name": name},
                    {"kind": "query", "op": "def-use", "name": name},
                    {
                        "kind": "synthesis",
                        "op": "rebind",
                        "name": name,
                        "body": rec["body"],
                        "summary": rec["summary"],
                    },
                ],
                "verify": {
                    "apply_ok": True,
                    "unchanged": frozen,
                    "probes": {"t_mono": True, "energy_after_steps_lt": rec["e1"] + 0.001},
                },
            }
        else:
            frozen = list(plant.get("frozen") or ["*session*", "gate"])
            hot = list(plant.get("hot") or ["tick"])
            pre = {
                "id": rec.get("sid"),
                "fd": rec.get("sfd"),
                "alive": bool(rec.get("sal", True)),
                "seq": rec.get("sseq", 0),
            }
            post = {
                "id": rec.get("sid2", rec.get("sid")),
                "fd": rec.get("sfd2", rec.get("sfd")),
                "alive": bool(rec.get("sal2", True)),
                "seq": rec.get("sseq2", rec.get("sseq", 0)),
            }
            q_ok = rec.get("okq", True)
            if q_ok is False:
                drop += 1
                continue
            if not session_should_keep(pre, post, name, keep_flag=True, q_ok=True, k=8):
                drop += 1
                continue
            sample = {
                "id": rec["id"],
                "input": {
                    "source": rec["source"],
                    "observe": {
                        "session": pre,
                        "hot": hot,
                        "frozen": frozen,
                    },
                },
                "target": [
                    {"kind": "query", "op": "find", "name": name},
                    {
                        "kind": "synthesis",
                        "op": "rebind",
                        "name": name,
                        "body": rec["body"],
                        "summary": rec["summary"],
                    },
                ],
                "verify": {"apply_ok": True, "probes": {"session_stable": True}},
            }
        try:
            validate_patch(sample["target"], observe=sample["input"]["observe"])
        except PatchError:
            drop += 1
            continue
        if sample["id"] in seen:
            continue
        append_jsonl(out_path, sample)
        seen.add(sample["id"])
        keep += 1
    print(f"farm: mode=world project={pid} keep={keep} drop={drop} -> {out_path}")
    return 0 if keep else 1


def _path_obs_hash(plant: dict, extra: str) -> str:
    return (
        "(json-encode (hash \"plant\" "
        + scheme_string(plant["id"])
        + ' "source" '
        + scheme_string(plant["source"])
        + " "
        + extra
        + "))"
    )


def emit_path_twin_driver(
    plant: dict, chain: list[dict], n_pre: int = 40, n_post: int = 40
) -> str:
    """One plant, depth hops on the SAME world. Replant only after the driver ends."""
    w0 = world_init_aura(plant)
    lines = [
        ";; path-mode twin-step — measured observe, no mid-hop reset",
        '(require "farm" all:)',
        "(define (num-or-false w k)",
        "  (try (let ((v (hash-ref w k))) (if (number? v) v #f)) (catch (e) #f)))",
        f"(set-code {scheme_string(plant['source'])})",
        "(eval-current)",
        f"(define *w* {w0})",
        "(define (go k)",
        "  (if (<= k 0) #t",
        "    (begin (set! *w* (step *w* (control *w*))) (go (- k 1)))))",
        f"(try (go {n_pre}) (catch (e) #f))",
        "(define *rb* #f)",
    ]
    for i, rw in enumerate(chain, start=1):
        name = rw.get("name") or "control"
        lines += [
            f"(define *epoch* {i})",
            "(if *w*",
            "  (begin",
            '    (display "PATH_OBS ")',
            "    (display "
            + _path_obs_hash(
                plant,
                '"epoch" *epoch* "t" (hash-ref *w* "t") "energy" (energy *w*) '
                '"sat" (num-or-false *w* "sat") "x2" (num-or-false *w* "x2")',
            )
            + ")",
            "    (newline))",
            '  (begin (display "PATH_DROP") (newline)))',
            f"(set! *rb* (try (mutate:rebind {scheme_string(name)} {scheme_string(rw['body'])} {scheme_string(rw['summary'])}) (catch (e) #f)))",
            "(if *rb* (try (eval-current) (catch (e) #f)) #f)",
            f"(try (go {n_post}) (catch (e) (set! *w* #f)))",
            "(if (and *rb* *w*)",
            "  (begin",
            '    (display "PATH_POST ")',
            "    (display (json-encode (hash \"ok\" #t \"epoch\" *epoch*",
            ' "t" (hash-ref *w* "t") "energy" (energy *w*)',
            ' "sat" (num-or-false *w* "sat") "x2" (num-or-false *w* "x2")',
            ' "name" '
            + scheme_string(name)
            + ' "summary" '
            + scheme_string(rw["summary"])
            + ' "body" '
            + scheme_string(rw["body"])
            + ")))",
            "    (newline))",
            '  (begin (display "PATH_POST ") (display (json-encode (hash "ok" #f "epoch" *epoch*))) (newline)))',
        ]
    lines.append("")
    return "\n".join(lines)


def emit_path_session_driver(plant: dict, chain: list[dict], k: int = 8) -> str:
    """One plant, depth hops on the SAME sess. Replant only after the driver ends."""
    lines = [
        ";; path-mode session-hot — measured observe, no mid-hop reset",
        f"(set-code {scheme_string(plant['source'])})",
        "(eval-current)",
        "(define *sess* *session*)",
        '(define *book* (hash "bid" 1 "ask" 3 "mid" 2 "spread" 2))',
        "(define *okq* #t)",
        "(define *out* #f)",
        "(define *rb* #f)",
        "(define (go i)",
        "  (if (<= i 0) #t",
        "    (begin",
        "      (set! *out* (try (tick *book* *sess*) (catch (e) #f)))",
        '      (if (and *out* (number? (hash-ref *out* "q")))',
        '        (set! *sess* (hash-ref *out* "sess"))',
        "        (set! *okq* #f))",
        "      (go (- i 1)))))",
    ]
    for i, rw in enumerate(chain, start=1):
        name = rw.get("name") or "tick"
        lines += [
            f"(define *epoch* {i})",
            "(if *sess*",
            "  (begin",
            '    (display "PATH_OBS ")',
            "    (display "
            + _path_obs_hash(
                plant,
                '"epoch" *epoch* "sid" (hash-ref *sess* "id") "sfd" (hash-ref *sess* "fd") '
                '"sal" (hash-ref *sess* "alive") "sseq" (try (hash-ref *sess* "seq") (catch (e) 0))',
            )
            + ")",
            "    (newline))",
            '  (begin (display "PATH_DROP") (newline)))',
            f"(set! *rb* (try (mutate:rebind {scheme_string(name)} {scheme_string(rw['body'])} {scheme_string(rw['summary'])}) (catch (e) #f)))",
            "(if *rb* (try (eval-current) (catch (e) #f)) #f)",
            "(set! *okq* #t)",
            f"(if *rb* (try (go {k}) (catch (e) (set! *okq* #f))) #f)",
            "(if (and *rb* *sess*)",
            "  (begin",
            '    (display "PATH_POST ")',
            "    (display (json-encode (hash \"ok\" #t \"epoch\" *epoch*",
            ' "sid" (hash-ref *sess* "id") "sfd" (hash-ref *sess* "fd")',
            ' "sal" (hash-ref *sess* "alive")',
            ' "sseq" (try (hash-ref *sess* "seq") (catch (e) 0))',
            ' "okq" *okq*',
            ' "name" '
            + scheme_string(name)
            + ' "summary" '
            + scheme_string(rw["summary"])
            + ' "body" '
            + scheme_string(rw["body"])
            + ")))",
            "    (newline))",
            '  (begin (display "PATH_POST ") (display (json-encode (hash "ok" #f "epoch" *epoch*))) (newline)))',
        ]
    lines.append("")
    return "\n".join(lines)


def _load_path_rewrites(pid: str) -> tuple[list[dict], list[dict]]:
    plants, rewrites = load_project(pid)
    neg = PROJECTS_ROOT / pid / "rewrites.neg.jsonl"
    extra: list[dict] = []
    if neg.is_file():
        extra = [json.loads(l) for l in neg.read_text(encoding="utf-8").splitlines() if l.strip()]
    return plants, rewrites + extra


def run_path(args: argparse.Namespace) -> int:
    """Vertical path depth-4: measured observe, energy-up → refuse, cut on probe fail."""
    pid = args.project
    if pid not in ("twin-step", "session-hot"):
        print("error: --mode path --project requires twin-step|session-hot", file=sys.stderr)
        return 2
    vertical = "twin" if pid == "twin-step" else "session"
    plants, rewrites = _load_path_rewrites(pid)
    keep_by_sum = {rw.get("summary"): rw.get("keep") is not False for rw in rewrites}
    depth = max(1, min(args.depth, 4))
    n_post = 40
    k_ticks = 8
    out_path = args.out if args.out != OUT else (ROOT / "data" / "raw" / f"farm-path-{pid}.jsonl")
    refuse_path = getattr(args, "refuse_out", None)
    keep = refuse_n = drop = 0
    seen = seen_ids(out_path)
    plants = plants[: args.rounds] if args.rounds else plants
    for plant in plants:
        chain = path_chain(plant, rewrites, depth, vertical)
        if not chain:
            continue
        if vertical == "twin":
            driver = emit_path_twin_driver(plant, chain, n_pre=40, n_post=n_post)
        else:
            driver = emit_path_session_driver(plant, chain, k=k_ticks)
        try:
            raw = run_aura(driver, timeout=min(args.timeout, 45))
        except PatchError as e:
            print(f"farm: path {plant.get('id')} {e}", flush=True)
            drop += 1
            continue
        hops: list[tuple[dict, dict | None]] = []
        pending_obs: dict | None = None
        for line in raw.splitlines():
            if line.startswith("PATH_DROP"):
                drop += 1
                pending_obs = None
                continue
            if line.startswith("PATH_OBS "):
                pending_obs = json.loads(line[len("PATH_OBS ") :])
            elif line.startswith("PATH_POST "):
                post = json.loads(line[len("PATH_POST ") :])
                hops.append((pending_obs or {}, post))
                pending_obs = None
        last = ""
        last_obs: dict | None = None
        frozen = list(plant.get("frozen") or (["step", "energy"] if vertical == "twin" else ["*session*", "gate"]))
        hot = list(plant.get("hot") or (["control"] if vertical == "twin" else ["tick"]))
        for obs, post in hops:
            name = post.get("name") or hot[0]
            if vertical == "twin":
                pre = {
                    "t": obs.get("t"),
                    "energy": obs.get("energy"),
                    "sat": obs.get("sat"),
                    "x2": obs.get("x2"),
                }
                post_m = {
                    "ok": post.get("ok", True),
                    "t": post.get("t"),
                    "energy": post.get("energy"),
                    "sat": post.get("sat"),
                    "x2": post.get("x2"),
                }
            else:
                pre = {
                    "session": {
                        "id": obs.get("sid"),
                        "fd": obs.get("sfd"),
                        "alive": bool(obs.get("sal", True)),
                        "seq": obs.get("sseq", 0),
                    }
                }
                post_m = {
                    "ok": post.get("ok", True),
                    "okq": post.get("okq", True),
                    "session": {
                        "id": post.get("sid"),
                        "fd": post.get("sfd"),
                        "alive": bool(post.get("sal", True)),
                        "seq": post.get("sseq", 0),
                    },
                }
            action = path_decide(
                pre,
                post_m,
                vertical,
                last=last,
                name=name,
                frozen=frozen,
                n_post=n_post,
                k=k_ticks,
                keep_flag=keep_by_sum.get(post.get("summary"), True),
            )
            epoch = obs.get("epoch") or post.get("epoch")
            if action in ("refuse", "worsen"):
                # Worsen: do not emit the rebind. Refuse gold uses measured post-step observe.
                if vertical == "twin":
                    src_obs = post if action == "worsen" else obs
                    observe = {
                        "t": src_obs.get("t"),
                        "energy": src_obs.get("energy"),
                        "hot": hot,
                        "frozen": frozen,
                        "epoch": epoch,
                    }
                    if _opt_num(src_obs.get("sat")) is not None:
                        observe["sat"] = src_obs["sat"]
                    prev_e = obs if action == "worsen" else last_obs
                    intent = path_intent_twin(src_obs, prev_e, refuse=True)
                    try:
                        why = (
                            "energy-up"
                            if float(src_obs.get("energy"))
                            >= float((prev_e or {}).get("energy", src_obs.get("energy")))
                            else "drift"
                        )
                    except (TypeError, ValueError):
                        why = "drift"
                    rname = hot[0]
                else:
                    sess = post_m.get("session") if action == "worsen" else pre["session"]
                    observe = {
                        "session": sess,
                        "hot": hot,
                        "frozen": frozen,
                        "epoch": epoch,
                    }
                    intent = path_intent_session(observe, refuse=True)
                    why = "drift"
                    rname = hot[0]
                sample = {
                    "id": f"path-{plant['id']}-e{epoch}-refuse",
                    "input": {
                        "source": plant["source"],
                        "intent": intent,
                        "observe": observe,
                    },
                    "target": [
                        {"kind": "query", "op": "find", "name": rname},
                        {
                            "kind": "refuse",
                            "op": "schema",
                            "name": rname,
                            "why": why,
                        },
                    ],
                    "verify": {"apply_ok": True, "probes": {"refused": True}},
                    "sft": True,
                    "meta": {"mode": "path", "epoch": epoch, "chain": plant["id"]},
                }
                try:
                    validate_patch(sample["target"], observe=observe)
                except PatchError:
                    drop += 1
                    last = "cut"
                    break
                blob = json.dumps(sample)
                if any(tok in blob for tok in ('"skip"', '"persist"', '"restore"', '"yield"')):
                    drop += 1
                    last = "cut"
                    break
                if sample["id"] not in seen:
                    append_jsonl(out_path, sample)
                    seen.add(sample["id"])
                    if refuse_path:
                        append_jsonl(refuse_path, sample)
                    refuse_n += 1
                last = "refuse"
                break
            if action == "cut":
                drop += 1
                last = "cut"
                break
            # keep
            if vertical == "twin":
                observe = {
                    "t": obs.get("t"),
                    "energy": obs.get("energy"),
                    "hot": hot,
                    "frozen": frozen,
                    "epoch": epoch,
                }
                if _opt_num(obs.get("sat")) is not None:
                    observe["sat"] = obs["sat"]
                intent = path_intent_twin(obs)
                target = [
                    {"kind": "query", "op": "find", "name": name},
                    {"kind": "query", "op": "def-use", "name": name},
                    {
                        "kind": "synthesis",
                        "op": "rebind",
                        "name": name,
                        "body": post["body"],
                        "summary": post["summary"],
                    },
                ]
                verify = {
                    "apply_ok": True,
                    "unchanged": frozen,
                    "probes": {"t_mono": True, "energy_after_steps_lt": post["energy"]},
                }
            else:
                observe = {
                    "session": pre["session"],
                    "hot": hot,
                    "frozen": frozen,
                    "epoch": epoch,
                }
                intent = path_intent_session(observe)
                target = [
                    {"kind": "query", "op": "find", "name": name},
                    {
                        "kind": "synthesis",
                        "op": "rebind",
                        "name": name,
                        "body": post["body"],
                        "summary": post["summary"],
                    },
                ]
                verify = {"apply_ok": True, "probes": {"session_stable": True}}
            sample = {
                "id": f"path-{plant['id']}-e{epoch}-{post.get('summary')}",
                "input": {
                    "source": plant["source"],
                    "intent": intent,
                    "observe": observe,
                },
                "target": target,
                "verify": verify,
                "sft": True,
                "meta": {"mode": "path", "epoch": epoch, "chain": plant["id"]},
            }
            try:
                validate_patch(sample["target"], observe=observe)
            except PatchError:
                drop += 1
                last = "cut"
                break
            blob = json.dumps(sample)
            if "skip" in blob or "persist" in blob or '"restore"' in blob or "yield" in blob:
                drop += 1
                last = "cut"
                break
            if sample["id"] not in seen:
                append_jsonl(out_path, sample)
                seen.add(sample["id"])
                keep += 1
            last = "keep"
            last_obs = obs
    print(
        f"farm: mode=path project={pid} keep={keep} refuse={refuse_n} drop={drop} "
        f"depth={depth} -> {out_path}"
    )
    return 0 if (keep or refuse_n) else 1


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--rounds", type=int, default=24, help="cap on attempts (pairs), not keeps")
    p.add_argument("--timeout", type=int, default=120, help="whole Aura process timeout seconds")
    p.add_argument(
        "--project",
        default="",
        help="catalog/projects/<id> (required for --mode world; path verticals)",
    )
    p.add_argument(
        "--mode",
        default="star",
        help="star | path | world (twin-step / session-hot)",
    )
    p.add_argument(
        "--depth",
        type=int,
        default=4,
        help="path-mode chain length before re-plant (capped at 4)",
    )
    p.add_argument("--limit-rewrites", type=int, default=0)
    p.add_argument(
        "--refuse-out",
        type=Path,
        default=None,
        help="optional extra jsonl for path-mode energy-up refuse golds",
    )
    p.add_argument("--out", type=Path, default=OUT)
    p.add_argument("--observe", type=Path, default=OBSERVE)
    p.add_argument("--spot-check", type=Path, default=None, help="re-apply keeps in this jsonl")
    p.add_argument(
        "--spot-frac",
        type=float,
        default=0.01,
        help="fraction of rows to re-apply (1.0 in tests; 0.01 default)",
    )
    args = p.parse_args(argv)

    if args.spot_check is not None:
        try:
            pick_bin()
        except SystemExit as e:
            print(str(e), file=sys.stderr)
            return 1
        return spot_check(args.spot_check, args.spot_frac)

    if args.mode not in ("star", "path", "world"):
        print("error: --mode must be star, path, or world", file=sys.stderr)
        return 2
    if args.mode == "world":
        return run_world(args)
    if args.mode == "path" and args.project:
        if args.project not in ("twin-step", "session-hot"):
            print(
                "error: --mode path --project requires twin-step|session-hot",
                file=sys.stderr,
            )
            return 2
        return run_path(args)
    depth = max(1, min(args.depth, 4))

    try:
        pick_bin()
    except SystemExit as e:
        print(str(e), file=sys.stderr)
        return 1

    plants = load_plants()
    rewrites = load_rewrites()
    if args.limit_rewrites:
        rewrites = rewrites[: args.limit_rewrites]
    plan = pairs(plants, rewrites)[: args.rounds]
    if not plan:
        print("farm: zero attempts (empty catalog pairs)", file=sys.stderr)
        return 1

    seen = seen_ids(args.out)
    driver = emit_driver(plan, mode=args.mode, depth=depth)
    # One process for all attempts (stdin driver; no per-sample spawn).
    try:
        out = run_aura(driver, timeout=args.timeout)
    except PatchError as e:
        print(f"farm: {e}", file=sys.stderr)
        return 1

    samples, observes = parse_stdout(out)
    if not samples and not observes:
        print("farm: zero attempts parsed from aura stdout", file=sys.stderr)
        return 1

    keep = illegal = 0
    plants_by_id = {p["id"]: p for p in plants}
    rws_by_sum = {}
    for rw in rewrites:
        rws_by_sum.setdefault(rw["summary"], []).append(rw)
    chain_plant = ""
    chain_round = 0
    for plant_id, row in samples:
        target = row.get("target")
        try:
            validate_patch(target)
        except PatchError:
            illegal += 1
            continue
        synth = target[-1]
        name = synth.get("name")
        summary = synth.get("summary")
        plant = plants_by_id.get(plant_id) or {}
        rw = (rws_by_sum.get(summary) or [{}])[0]
        sid = make_id(plant or {"id": plant_id or "x"}, rw or {"id": summary}, name)
        if sid in seen:
            continue
        if "input" not in row or "source" not in (row.get("input") or {}):
            illegal += 1
            continue
        if not (row.get("verify") or {}).get("apply_ok"):
            illegal += 1
            continue
        row["id"] = sid
        if args.mode == "path":
            if plant_id != chain_plant:
                chain_plant = plant_id
                chain_round = 0
            chain_round += 1
            row["meta"] = {
                "chain": plant_id,
                "round": chain_round,
                "mode": "path",
            }
        append_jsonl(args.out, row)
        seen.add(sid)
        keep += 1

    for ob in observes:
        append_jsonl(args.observe, ob)

    print(
        f"farm: attempts={len(plan)} keep={keep} observe={len(observes)} "
        f"illegal={illegal} mode={args.mode} -> {args.out}"
    )
    return 0 if keep or observes or samples else 1


if __name__ == "__main__":
    raise SystemExit(main())
