#!/usr/bin/env python3
"""Run the Aura teacher: multi-agent lesson fanout, then host apply-verify."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from apply import apply_patch, pick_bin, pick_lib
from edsl_patch import PatchError, aura_hash, lesson_to_sample, validate_patch

SEEDS = ROOT / "lessons" / "seeds.jsonl"


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def emit_driver(seeds: list[dict]) -> str:
    hashes = "\n    ".join(aura_hash(s) for s in seeds)
    return "\n".join(
        [
            ";; generated by scripts/teach.py",
            '(require "teacher" all:)',
            "(define *seeds*",
            f"  (list {hashes}))",
            "(teacher:run *seeds*)",
            "",
        ]
    )


def run_teacher(seeds: list[dict], *, timeout: int = 60) -> tuple[str, list[dict]]:
    bin_path = pick_bin()
    lib = pick_lib()
    env = os.environ.copy()
    env["AURA_PATH"] = f"{ROOT / 'lib'}:{lib}"
    env["AURA_SANDBOX"] = env.get("AURA_SANDBOX") or "off"
    env["AURA_PIPELINE_STRICT"] = env.get("AURA_PIPELINE_STRICT") or "0"
    with tempfile.TemporaryDirectory(prefix="edsl-teach-") as tmp:
        drv = Path(tmp) / "teacher-run.aura"
        drv.write_text(emit_driver(seeds), encoding="utf-8")
        proc = subprocess.run(
            [str(bin_path), str(drv)],
            cwd=tmp,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        out = (proc.stdout or "") + (("\n" + proc.stderr) if proc.stderr else "")
        if proc.returncode != 0:
            raise PatchError(f"teacher aura exit {proc.returncode}: {out[-2000:]}")
        mode = "unknown"
        lessons = []
        for line in out.splitlines():
            if line.startswith("TEACHER_MODE "):
                mode = line[len("TEACHER_MODE ") :].strip()
            elif line.startswith("TEACHER_LESSON "):
                lessons.append(json.loads(line[len("TEACHER_LESSON ") :]))
        return mode, lessons


def verify_lessons(lessons: list[dict]) -> list[dict]:
    kept = []
    seen = set()
    for les in lessons:
        try:
            sample = lesson_to_sample(les)
            validate_patch(sample["target"])
        except (PatchError, KeyError, TypeError):
            continue
        key = (sample["input"]["source"], json.dumps(sample["target"], sort_keys=True))
        if key in seen:
            continue
        seen.add(key)
        try:
            result = apply_patch(sample["input"]["source"], sample["target"])
        except PatchError:
            continue
        if not result.get("ok"):
            continue
        sample["verify"] = {
            "apply_ok": True,
            "expected_source": result.get("source") or "",
        }
        kept.append(sample)
    return kept


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--seeds", type=Path, default=SEEDS)
    p.add_argument("--out", type=Path, default=ROOT / "data" / "raw" / "teacher.jsonl")
    p.add_argument("--dump-lessons", type=Path, help="write raw fanout lessons")
    args = p.parse_args(argv)

    seeds = read_jsonl(args.seeds)
    if not seeds:
        print("error: no seeds", file=sys.stderr)
        return 1
    mode, lessons = run_teacher(seeds)
    if args.dump_lessons:
        write_jsonl(args.dump_lessons, lessons)
    kept = verify_lessons(lessons)
    write_jsonl(args.out, kept)
    print(
        f"teach: mode={mode} fanout={len(lessons)} "
        f"verified={len(kept)} seeds={len(seeds)} -> {args.out}"
    )
    return 0 if kept else 1


if __name__ == "__main__":
    raise SystemExit(main())
